<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationIcon>VERT_logo_bigrradio.ico</ApplicationIcon>
		<SelfContained>true</SelfContained>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="VERT_logo_bigrradio.ico" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="VERT_logo_bigrradio.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
		<PackageReference Include="LibVLCSharp" Version="3.10.1" />
		<PackageReference Include="Photino.NET" Version="4.0.16" />
	</ItemGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64' Or $(RuntimeIdentifier.StartsWith('win'))">
		<PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
	</ItemGroup>
	
	<ItemGroup>
		<None Update="wwwroot/**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>